import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://playwright-mastery-academy-app.vercel.app/practice');
  await page.getByRole('main').filter({ hasText: 'HomeCurriculumTestimonialsPracticeEnroll' }).getByRole('main').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('link', { name: 'Core UI > Sandbox Basic' }).click();
  await page.getByRole('heading', { name: 'Click, Double Click, Hover,' }).click();
  await page.getByTestId('double-click-btn').click();
  await page.getByTestId('double-click-btn').dblclick();
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByTestId('double-click-btn').press('ArrowDown');
  await page.getByText('Waiting for single click.').click();
  await expect(page.getByTestId('single-click-status')).toContainText('Waiting for single click.');
});